---
output: pdf_document
---

```{r}
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
library(spASE)
library(viridis)
library(Matrix)
library(latex2exp)
library(RColorBrewer)
library(xtable)
set.seed(1337)

expit <- function(x) {
  return(exp(x)/(1+exp(x)))
}
```

```{r}
# xchr annotations 
xchr <- read.delim('./data/MGImarkerQuery_20190611_114216.txt')$Symbol
```

```{r}
# Slide-seq data
# puck 4 needs to be rotated and shifted
load('./pucks.3-4.spatial.RData')
puck3.spatial <- puck3.spatial %>%
  mutate(total = CAST+X129) %>%
  mutate(X = xcoord/1000, Y = ycoord/1000)
puck4.spatial <- puck4.spatial %>%
  mutate(total = CAST+X129) %>%
  mutate(X = xcoord/1000, Y = ycoord/1000)


angle <- 261*pi/180
x.shift <- 0.37
y.shift <- -0.16
x.center <- 3.25
y.center <- 3.025
# rotate and shift puck 4
new.X <- (puck4.spatial$X-x.center)*cos(angle) - (puck4.spatial$Y-y.center)*sin(angle)+x.center + x.shift
new.Y <- (puck4.spatial$X-x.center)*sin(angle) + (puck4.spatial$Y-y.center)*cos(angle)+y.center + y.shift
puck4.spatial$X <- new.X
puck4.spatial$Y <- new.Y

# load in RCTD results
rctd.results.puck3 <- readRDS('rctd_puck_3.rds')
coords <- puck3.spatial %>%
  dplyr::select(X, Y, bead, total) %>%
  group_by(X, Y, bead) %>%
  summarise(nUMI = sum(total))
puck3.rctd <- rctd.results.puck3$results_df %>%
  mutate(bead = rownames(rctd.results.puck3$results_df)) %>%
  left_join(coords) %>%
  filter(spot_class == 'singlet')
rctd.results.puck4 <- readRDS('rctd_puck_4.rds')
coords <- puck4.spatial %>%
  dplyr::select(X, Y, bead, total) %>%
  group_by(X, Y, bead) %>%
  summarise(nUMI = sum(total))
puck4.rctd <- rctd.results.puck4$results_df %>%
  mutate(bead = rownames(rctd.results.puck4$results_df)) %>%
  left_join(coords) %>%
  filter(spot_class == 'singlet')

# combine RCTD annotations and both pucks
puck3.spatial <- left_join(puck3.spatial, puck3.rctd %>% dplyr::select(bead, first_type, spot_class), by = 'bead')
puck4.spatial <- left_join(puck4.spatial, puck4.rctd %>% dplyr::select(bead, first_type, spot_class), by = 'bead')

joint <- bind_rows(puck3.spatial, puck4.spatial)
joint <- joint %>%
  filter(!grepl('mt-',gene)) %>% 
  filter(bead!='TTTTTTTTTTTTTT') %>%
  filter(bead!='GGGGGGGGGGGGGG') %>%
  mutate(gene = as.factor(as.character(gene)), bead = as.factor(as.character(bead)))

# get locations at a grid of points
xcoords <- seq(min(joint$X), max(joint$X), by = 0.1)
ycoords <- seq(min(joint$Y), max(joint$Y), by = 0.1)
predictCoords <- expand.grid(xcoords, ycoords)
colnames(predictCoords) <- c('X', 'Y')
predictCoords <- data.frame(predictCoords) %>%
  filter(((X-3.2)^2+(Y-3.1)^2<=2.3^2) | ((X-x.center-x.shift)^2+(Y-y.center-y.shift)^2<=2.3^2))

singlets <- joint %>% 
  filter(spot_class == 'singlet') %>%
  mutate(gene = as.factor(as.character(gene)), bead = as.factor(as.character(bead)))
```


```{r}
# plot a map of cell types called from RCTD
# make a palette out of Set1 and 2
# remove mural b/c there's only 156 of them
# also remove ependymal b/c not visible 
nomural <- singlets %>% filter(first_type!='Mural', first_type!='Ependymal')
mypal <- data.frame(first_type=unique(nomural$first_type),fill=c(brewer.pal(7, 'Set1'), brewer.pal(8, 'Set2'))) %>%
  arrange(first_type)
mypal$fill[mypal$first_type=='Polydendrocyte'] <- '#000000'
mypal$fill[mypal$first_type=='Entorihinal'] <- '#FFD700'
mypal$fill <- factor(mypal$fill, levels=unique(mypal$fill))
nomural %>%
  dplyr::select(X,Y,first_type) %>%
  distinct() %>%
  left_join(mypal, by='first_type') %>%
  arrange(first_type) %>%
  mutate(first_type = factor(first_type, levels=unique(mypal$first_type))) %>%
  ggplot(aes(x = X, y= Y)) +
  geom_point(aes(color=fill),size=0.2) +
  scale_color_identity(guide='legend', name='', labels=(mypal%>%arrange(fill)%>%
  mutate(first_type = gsub('_',' ',first_type)) %>%
  mutate(first_type = gsub('Denate','Dentate',first_type))%>%mutate(first_type = gsub('Microglia Macrophages','Microglia/Macrophages',first_type))%>%mutate(gsub('Entorihinal','Entorhinal',first_type))%>%pull(first_type))) +
  theme_classic() +
  guides(colour = guide_legend(ncol=2,override.aes = list(size=3))) +
  theme(legend.position='none') +
  xlab('x1') +
  ylab('x2')
ggsave('figure4a.png', width=3,height=3,units='in')
```


```{r}
# first use all pixels, spatial coordinates
mcast <- with(joint, sparseMatrix(i = as.numeric(gene), j = as.numeric(bead), x=CAST, dimnames=list(levels(gene),levels(bead))))
m129 <- with(joint, sparseMatrix(i = as.numeric(gene), j = as.numeric(bead), x=X129, dimnames=list(levels(gene),levels(bead))))
covariates <- joint%>% dplyr::select(bead, X, Y) %>% distinct() 
# filter out beads with more than two locations
dupebeads <- covariates %>% group_by(bead) %>% summarise(n=n()) %>% filter(n>1) %>% pull(bead)
covariates <- covariates %>% filter(!(bead %in% dupebeads))
res15.nocelltype <- spase(mcast, m129, covariates, cores=2, df=15, min.umi=400) # use 400 to catch Xist for plotting, but filter to 1,000 UMI for the results
```

```{r}
result.nocelltype <- res15.nocelltype$result %>%
  filter(qval <= 0.01) %>%
  filter(totalUMI >= 1000) %>%
  arrange(qval)
result.nocelltype$xchr <- ifelse(result.nocelltype$gene %in% xchr, T, F)
# total number of significant genes with min total UMI 1000, min pixels 100:
nrow(result.nocelltype)
# total number of x chromosome genes 
sum(result.nocelltype$xchr)
xtable(result.nocelltype %>% dplyr::select(gene,totalUMI,chisq.p,qval,xchr),display=c('d', 's', 'd', 'e', 'e', 's')) #supp table 2
```

```{r}
# repeat above two blocks for k=5, 10, 20 to see if reproducible
# THIS TAKES A WHILE
res5.nocelltype <- spase(mcast, m129, covariates, cores=2, df=5, min.umi=400)
result.nocelltype.5 <- res5.nocelltype$result %>%
  filter(qval <= 0.01) %>%
  filter(totalUMI >= 1000) %>%
  arrange(qval)
res10.nocelltype <- spase(mcast, m129, covariates, cores=2, df=10, min.umi=400)
result.nocelltype.10 <- res10.nocelltype$result %>%
  filter(qval <= 0.01) %>%
  filter(totalUMI >= 1000) %>%
  arrange(qval)
res20.nocelltype <- spase(mcast, m129, covariates, cores=2, df=20, min.umi=400)
result.nocelltype.20 <- res20.nocelltype$result %>%
  filter(qval <= 0.01) %>%
  filter(totalUMI >= 1000) %>%
  arrange(qval)
```

```{r}
result.nocelltype.5$xchr <- ifelse(result.nocelltype.5$gene %in% xchr, T, F)
# total number of significant genes with min total UMI 1000, min pixels 100:
nrow(result.nocelltype.5)
# total number of x chromosome genes 
sum(result.nocelltype.5$xchr)
xtable(result.nocelltype.5 %>% dplyr::select(gene,totalUMI,chisq.p,qval,xchr),display=c('d', 's', 'd', 'e', 'e', 's'))
```

```{r}
result.nocelltype.10$xchr <- ifelse(result.nocelltype.10$gene %in% xchr, T, F)
# total number of significant genes with min total UMI 1000, min pixels 100:
nrow(result.nocelltype.10)
# total number of x chromosome genes 
sum(result.nocelltype.10$xchr)
xtable(result.nocelltype.10 %>% dplyr::select(gene,totalUMI,chisq.p,qval,xchr),display=c('d', 's', 'd', 'e', 'e', 's'))
```

```{r}
result.nocelltype.20$xchr <- ifelse(result.nocelltype.20$gene %in% xchr, T, F)
# total number of significant genes with min total UMI 1000, min pixels 100:
nrow(result.nocelltype.20)
# total number of x chromosome genes 
sum(result.nocelltype.20$xchr)
xtable(result.nocelltype.20 %>% dplyr::select(gene,totalUMI,chisq.p,qval,xchr),display=c('d', 's', 'd', 'e', 'e', 's'))
```

```{r}
# merge the xchr genes except for xist 
xchr.idx <- which(rownames(mcast) %in% xchr)
xchr.idx <- xchr.idx[-which(xchr.idx == (which(rownames(mcast)=='Xist')))]
mcast.xchr <- colSums(mcast[xchr.idx,])
m129.xchr <- colSums(m129[xchr.idx,])
mcast.xchr <- t(as.matrix(mcast.xchr))
m129.xchr <- t(as.matrix(m129.xchr))
rownames(mcast.xchr) <- 'merged xchr'
rownames(m129.xchr) <- 'merged xchr'
res.xchr <- spase(mcast.xchr, m129.xchr, covariates, cores=1, df=30)
```

```{r}
plotSpase(mcast.xchr, m129.xchr, covariates, res.xchr, coords=predictCoords, cross.x1=3, cross.x2=3, save='figure3xchrmerged')
```

```{r}
plotSpase(mcast, m129, covariates, res15.nocelltype, genes=c('Xist', 'Gprasp1', 'Tspan7', 'Plp1'), coords=predictCoords,cross.x1=3, cross.x2=3, save='figure3xchr')
```

```{r}
mcast <- with(singlets, sparseMatrix(i = as.numeric(gene), j = as.numeric(bead), x=CAST, dimnames=list(levels(gene),levels(bead))))
m129 <- with(singlets, sparseMatrix(i = as.numeric(gene), j = as.numeric(bead), x=X129, dimnames=list(levels(gene),levels(bead))))
covariates <- singlets%>% dplyr::select(bead, first_type) %>% distinct() 
ss <- scase(mcast, m129, min.cells=300, cores=2)
```

```{r, eval = F}
# only calculate LRT with singlets that have cell type assigned
mcast <- with(singlets, sparseMatrix(i = as.numeric(gene), j = as.numeric(bead), x=CAST, dimnames=list(levels(gene),levels(bead))))
m129 <- with(singlets, sparseMatrix(i = as.numeric(gene), j = as.numeric(bead), x=X129, dimnames=list(levels(gene),levels(bead))))
covariates <- singlets%>% dplyr::select(bead, X, Y, first_type) %>% distinct() 
res15_singlets_nocelltype <- spase(mcast, m129, covariates[,1:3],cores=2, df=15)
res15_singlets_celltype<-spase(mcast, m129, covariates, cores=2, df=15)
```

```{r}
# get individual CI results for each cell type using scase
# which ones are significant at qval<0.01
signif0.01 <- res15_singlets_nocelltype$result %>% arrange(qval) %>% filter(qval<0.01)
signif0.01$xchr <- ifelse(signif0.01$gene%in%xchr, T, F)
sccov <- covariates[,c(1,4)]
sccov$first_type <- as.factor(sccov$first_type)
res_celltype_sc <- scase(mcast, m129, sccov, cores=2, genes = signif0.01$gene[!signif0.01$xchr])
```

```{r}
# for each gene, plot the estimated p, CI, and total UMI
res_celltype_sc <- res_celltype_sc %>%
  mutate(p.low = expit(logit.p-2*logit.p.sd),
         p.high = expit(logit.p+2*logit.p.sd),
         p = expit(logit.p)) %>%
  left_join(mypal, by =c('lvl'='first_type'))

res_celltype_sc %>%
  ggplot(aes(y = totalUMI)) +
  geom_point(aes(x = p, color=fill)) +
  geom_errorbarh(aes(xmin = p.low, xmax=p.high, color=fill)) +
  scale_color_identity() +
  geom_vline(xintercept=0.5, lty='dashed', color='grey') +
  facet_wrap(gene ~ ., scales='free') +
  scale_x_continuous(limits=c(0,1),breaks=c(0,0.25,0.50,0.75,1)) +
  theme_bw()
```

```{r}
# figure 4x, plotting the non-xchr cell type points with CIs
res_celltype_sc %>%
  ggplot(aes(y = gene)) +
  geom_errorbarh(aes(xmin = p.low, xmax = p.high, color = fill),
                position=position_dodge(width=0.9)) +
  geom_point(aes(x=p, color=fill), position=position_dodge(width=0.9), size=0.5) +
  geom_vline(xintercept=0.5, lty='dashed') +
  geom_hline(yintercept=1.5) +
  geom_hline(yintercept=2.5) +
  geom_hline(yintercept=3.5) +
  geom_hline(yintercept=4.5) +
  geom_hline(yintercept=5.5) +
  geom_hline(yintercept=6.5) +
  scale_color_identity() +
  scale_x_continuous(limits=c(0,1),breaks=c(0,0.25,0.50,0.75,1)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, hjust=1)) +
  ylab('')
ggsave(filename='figure4b.png', height=4, width=1.5, units='in')
```

```{r}
# just plot for ptgds
sccov <- covariates[,c(1,4)]
sccov$first_type <- as.factor(sccov$first_type)
res_celltype_ptgds <- scase(mcast, m129, sccov, cores=2, genes = 'Ptgds')
```

```{r}
res_celltype_ptgds %>%
  mutate(p.low = expit(logit.p-2*logit.p.sd),
         p.high = expit(logit.p+2*logit.p.sd),
         p = expit(logit.p)) %>%
  left_join(mypal, by=c('lvl'='first_type')) %>%
  ggplot() +
  geom_point(aes(x = p, y = totalUMI, color=fill),size=3) +
  geom_errorbarh(aes(xmin = p.low, xmax = p.high, y=totalUMI, color = fill)) +
  scale_x_continuous(limits=c(0,1),breaks=c(0,0.25,0.50,0.75,1)) +
  scale_color_identity() +
  xlab('estimated p maternal') +
  ylab('total UMI') +
  geom_vline(xintercept=0.5, lty='dashed',color='grey') +
  theme_classic()
ggsave('figure4b-ptgds-ci.png', height=2.5, width=2.5, units='in')
```

```{r}
# plot only oligodendrocytesfor Ptgds
both.idx <- which(covariates$first_type=='Oligodendrocyte')
#both.idx <- c(both.idx, grep('Endothelial', covariates$first_type))
both.beads <- covariates$bead[both.idx]
y <- mcast['Ptgds',both.beads]
total <- y+m129['Ptgds',both.beads]
covari <- covariates[both.idx,]
idx <- which(total>0)
y<-y[idx]; total<-total[idx]; covari<-covari[idx,]
#covari$shape <- ifelse(covari$first_type=='Oligodendrocyte',21,24)
ggplot(cbind(data.frame(y=y, total=total), covari),
       aes(x=X,y=Y)) +
  geom_point(aes(fill=y/total,size=total), shape=21, color='black') +
  scale_fill_gradient2(name='CAST/total', low='blue', mid='white', high='red',
                       midpoint=0.5, limits=c(0,1)) +
  scale_size_continuous(limits=c(1,40), breaks=c(1,10,20,30,40), range=c(2,4)) +
  xlab('x1') +
  ylab('x2') +
  theme_classic() +
  theme(legend.position='bottom')
ggsave('figure4ptgds-oligo.png', height=3,width=5)
```

```{r}
# plot other  cells for Ptgds
endo.idx <- which(!grepl('Oligo', covariates$first_type))
endo.beads <- covariates$bead[endo.idx]
y <- mcast['Ptgds',endo.beads]
total <- y+m129['Ptgds',endo.beads]
covari <- covariates[endo.idx,]
idx <- which(total>0)
y<-y[idx]; total<-total[idx]; covari<-covari[idx,]
ggplot(cbind(data.frame(y=y, total=total), covari),
       aes(x=X,y=Y)) +
  geom_point(aes(fill=y/total,size=total), shape=21, color='black') +
  scale_fill_gradient2(name='y/total', low='blue', mid='white', high='red',
                       midpoint=0.5, limits=c(0,1)) +
  scale_size_continuous(limits=c(1,40), breaks=c(1,10,20,30,40), range=c(2,4)) +
  scale_x_continuous(limits=c(1,6), breaks=seq(1,6,1)) +
  scale_y_continuous(limits=c(1,5), breaks=seq(1,5,1)) +
  theme_classic() +
  facet_wrap(first_type ~ .) +
  ggtitle(paste('Ptgds Other Cell Types'))
ggsave('figure4ptgds-other.png', height=2.5,width=3.5)
```

```{r}
# plot interneurons for Sst
inter.idx <- which(grepl('Interneuron', covariates$first_type))
inter.beads <- covariates$bead[inter.idx]
y <- mcast['Sst',inter.beads]
total <- y+m129['Sst',inter.beads]
covari <- covariates[inter.idx,]
idx <- which(total>0)
y<-y[idx]; total<-total[idx]; covari<-covari[idx,]
ggplot(cbind(data.frame(y=y, total=total), covari),
       aes(x=X,y=Y)) +
  geom_point(aes(fill=y/total,size=total), shape=21, color='black') +
  scale_fill_gradient2(name='y/total', low='blue', mid='white', high='red',
                       midpoint=0.5, limits=c(0,1)) +
  scale_size_continuous(limits=c(1,40), breaks=c(1,10,20,30,40), range=c(2,4)) +
  scale_x_continuous(limits=c(1,6), breaks=seq(1,6,1)) +
  scale_y_continuous(limits=c(1,5), breaks=seq(1,5,1)) +
  theme_classic() +
  ggtitle(paste('Sst Interneuron Cells'))
ggsave('figure4sst-inter.png', height=2.5,width=3.5)
```


```{r}
# calculate number significant at q=0.01 before and after including cell type
# also fraction of them that are xchr
# before cell type
res15.nocelltype$result %>%
  arrange(qval) %>%
  filter(qval <= 0.01) %>%
  filter(totalUMI>=500) %>%
  left_join(data.frame(gene=xchr, type='xchr')) %>%
  group_by(type) %>%
  summarise(count=n())
```

```{r}
# after cell type
res15.celltype$result %>%
  arrange(qval) %>%
  filter(qval <= 0.1) %>%
  filter(totalUMI>=500) %>%
  left_join(data.frame(gene=xchr, type='xchr')) 
```
